### ISSUE TITLE
Possible Corrupted Wallet?

### ISSUE THREAD

**Issue by roxcursed** [HardCorePawn/multibit_recovery#5]
Hi HCP,

First of all can I say thanks a million for putting this tool together. Really appreciate the support.

I have a multibit classic wallet which I can not get into. Like many others I think I know the password and I have tried your tool to test it.

When trying random passwords that I know are not correct I simply get the incorrect password error. When I try the _decrypt_multibit_classic_walletkeys.py_ routine with the password I believe to be correct I get:

```
C:\Users\xxxx\Desktop\multibit_recovery-master>decrypt_multibit_classic_walletkeys.py wallet.wallet
File NOT Encrypted
--------------------------------------------------------------------------------
Keys are encrypted
terminal does not support UTF; passwords with non-ASCII chars might not work
This wallet file is encrypted, please enter its password:

Pubkey: 1QEaBE4RzBuM2RtsVAyvq27DwoGmSjPhEY
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\multibit_recovery-master\decrypt_multibit_classic_walletkeys.py", line 215, in <module>
    wallet = load_wallet(wallet_file, get_password)
  File "C:\Users\Russell\Desktop\multibit_recovery-master\decrypt_multibit_classic_walletkeys.py", line 172, in load_wallet
    print("Privkey: " + bitcoin.encode_privkey(privkey, 'wif_compressed'))
  File "C:\Python27\lib\site-packages\bitcoin\main.py", line 224, in encode_privkey
    return encode_privkey(decode_privkey(priv), formt, vbyte)
  File "C:\Python27\lib\site-packages\bitcoin\main.py", line 237, in decode_privkey
    if not formt: formt = get_privkey_format(priv)
  File "C:\Python27\lib\site-packages\bitcoin\main.py", line 217, in get_privkey_format
    bin_p = b58check_to_bin(priv)
  File "C:\Python27\lib\site-packages\bitcoin\main.py", line 427, in b58check_to_bin
    assert bin_dbl_sha256(data[:-4])[:4] == data[-4:]
AssertionError
```

When I try the _decrypt_multibit_classic_keys.py_ routine with the password I believe to be correct I get:

`C:\Users\xxxx\Desktop\multibit_recovery-master>decrypt_multibit_classic_keys.py multibit-20130706142010.key
terminal does not support UTF; passwords with non-ASCII chars might not work
This wallet file is encrypted, please enter its password:
S@ñ2ý.%ð3_)¶j¦Æõ0°èßïHk}ÇV¼>ª¦^+ýC+L
ê àã~HB_/)ª%"BNðØ'§u9UÚYF+6<m~»pO7`

I have been reading a bit about corrupted wallets. Do you think that could be what's happening here?

Any help greatly appreciated.

**Comment by anywalletrecovery** [comment]
@roxcursed 
I have machine for multibit wallet and can recover multibit password

**Comment by roxcursed** [comment]
@anywalletrecovery Hi there. I never expected to receive a response to this over 4 years later.  I still have the wallet. Can you let me know what would be involved?

**Comment by anywalletrecovery** [comment]
@roxcursed 
Yeah I was browsing some pages and I happened to read your issue, and I thought you might still have the problem.
I have recovered many multibit wallets. and some of the had corrupt file. for fast response text me in telegram or gmail
Telegram: @walletrecover 
anywalletrecovery@gmail.com

**Comment by roxcursed** [comment]
@anywalletrecovery Thanks. I sent an email to anywalletrecovery@gmail.com

**Comment by CryptoXT** [comment]
@roxcursed You can try contacting Sankopolo at Laterbtc@gmail.com
His thread on the Russian forum https://forum.bits.media/index.php?/topic/61780
He is a highly qualified specialist and has been working for many years.
